[package]
name = "cranpose-ui-graphics"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
description = "Pure math/data for drawing & units in Cranpose"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints]
workspace = true

[dependencies]
arrayvec = "0.7.6"
bytemuck = { workspace = true }
thiserror = "2.0.18"

[features]
default = []
