//! Auto-generated robot test from recording
//! Generated at: timestamp
//! Events: 331

use compose_app::AppLauncher;
use std::time::Duration;

fn main() {
    AppLauncher::new()
        .with_headless(true)
        .with_test_driver(|robot| {
            std::thread::sleep(Duration::from_millis(500));
            let _ = robot.wait_for_idle();

            std::thread::sleep(Duration::from_millis(385));
            let _ = robot.mouse_move(399.5, 288.7);
            std::thread::sleep(Duration::from_millis(778));
            let _ = robot.mouse_move(399.1, 288.1);
            std::thread::sleep(Duration::from_millis(16));
            let _ = robot.mouse_move(398.6, 286.7);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(398.6, 284.9);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(398.6, 283.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(398.2, 281.2);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(397.7, 278.9);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(397.7, 277.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(397.2, 276.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(396.8, 274.3);
            std::thread::sleep(Duration::from_millis(97));
            let _ = robot.mouse_move(396.3, 271.9);
            let _ = robot.mouse_move(395.9, 270.1);
            let _ = robot.mouse_move(394.9, 267.8);
            let _ = robot.mouse_move(393.4, 264.8);
            let _ = robot.mouse_move(392.4, 261.7);
            let _ = robot.mouse_move(390.3, 258.5);
            let _ = robot.mouse_move(388.7, 255.3);
            let _ = robot.mouse_move(386.6, 252.7);
            let _ = robot.mouse_move(384.6, 250.7);
            let _ = robot.mouse_move(382.6, 248.3);
            let _ = robot.mouse_move(380.0, 245.6);
            let _ = robot.mouse_move(376.7, 242.9);
            std::thread::sleep(Duration::from_millis(6));
            let _ = robot.mouse_move(373.4, 240.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(370.0, 237.8);
            std::thread::sleep(Duration::from_millis(35));
            let _ = robot.mouse_move(365.9, 234.9);
            let _ = robot.mouse_move(362.5, 232.6);
            let _ = robot.mouse_move(359.2, 229.9);
            let _ = robot.mouse_move(355.8, 227.6);
            let _ = robot.mouse_move(351.7, 224.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(346.7, 221.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(342.4, 217.9);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(337.5, 214.8);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(333.9, 211.8);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(329.8, 208.9);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(326.3, 206.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(322.9, 203.1);
            std::thread::sleep(Duration::from_millis(89));
            let _ = robot.mouse_move(318.7, 199.6);
            let _ = robot.mouse_move(314.2, 195.1);
            let _ = robot.mouse_move(309.8, 191.3);
            let _ = robot.mouse_move(306.0, 186.9);
            let _ = robot.mouse_move(303.0, 183.3);
            let _ = robot.mouse_move(300.2, 179.9);
            let _ = robot.mouse_move(297.4, 176.5);
            let _ = robot.mouse_move(293.8, 172.3);
            let _ = robot.mouse_move(290.7, 168.1);
            let _ = robot.mouse_move(287.0, 163.8);
            let _ = robot.mouse_move(284.0, 159.5);
            std::thread::sleep(Duration::from_millis(6));
            let _ = robot.mouse_move(281.1, 156.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(278.2, 152.6);
            std::thread::sleep(Duration::from_millis(35));
            let _ = robot.mouse_move(276.0, 149.2);
            let _ = robot.mouse_move(274.5, 146.7);
            let _ = robot.mouse_move(273.0, 144.2);
            let _ = robot.mouse_move(271.6, 142.3);
            let _ = robot.mouse_move(270.6, 140.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(269.2, 137.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(267.8, 135.7);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(266.3, 132.7);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(264.7, 128.9);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(263.1, 126.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(262.1, 123.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(261.1, 120.9);
            std::thread::sleep(Duration::from_millis(89));
            let _ = robot.mouse_move(260.2, 119.0);
            let _ = robot.mouse_move(258.8, 116.7);
            let _ = robot.mouse_move(258.3, 115.3);
            let _ = robot.mouse_move(256.9, 113.4);
            let _ = robot.mouse_move(256.5, 112.0);
            let _ = robot.mouse_move(255.5, 110.2);
            let _ = robot.mouse_move(255.1, 108.4);
            let _ = robot.mouse_move(254.2, 107.0);
            let _ = robot.mouse_move(253.7, 105.1);
            let _ = robot.mouse_move(253.2, 103.3);
            let _ = robot.mouse_move(252.8, 101.4);
            std::thread::sleep(Duration::from_millis(6));
            let _ = robot.mouse_move(252.3, 100.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(251.9, 98.2);
            std::thread::sleep(Duration::from_millis(19));
            let _ = robot.mouse_move(251.4, 96.4);
            let _ = robot.mouse_move(250.9, 94.5);
            let _ = robot.mouse_move(250.5, 92.7);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(250.0, 90.8);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(249.1, 89.4);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(248.6, 87.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(248.2, 86.2);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(247.7, 84.4);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(247.7, 82.5);
            std::thread::sleep(Duration::from_millis(13));
            let _ = robot.mouse_move(247.2, 81.1);
            std::thread::sleep(Duration::from_millis(100));
            let _ = robot.mouse_move(246.8, 78.8);
            let _ = robot.mouse_move(246.3, 77.4);
            let _ = robot.mouse_move(246.3, 75.6);
            let _ = robot.mouse_move(245.9, 73.7);
            let _ = robot.mouse_move(245.4, 72.4);
            let _ = robot.mouse_move(245.4, 71.0);
            let _ = robot.mouse_move(244.9, 70.0);
            let _ = robot.mouse_move(244.5, 68.7);
            let _ = robot.mouse_move(244.5, 67.7);
            let _ = robot.mouse_move(244.5, 66.4);
            std::thread::sleep(Duration::from_millis(6));
            let _ = robot.mouse_move(244.0, 65.4);
            std::thread::sleep(Duration::from_millis(32));
            let _ = robot.mouse_move(244.0, 64.7);
            std::thread::sleep(Duration::from_millis(28));
            let _ = robot.mouse_down();
            std::thread::sleep(Duration::from_millis(33));
            let _ = robot.mouse_up();
            std::thread::sleep(Duration::from_millis(355));
            let _ = robot.mouse_move(243.5, 64.7);
            std::thread::sleep(Duration::from_millis(24));
            let _ = robot.mouse_move(242.3, 65.1);
            std::thread::sleep(Duration::from_millis(16));
            let _ = robot.mouse_move(240.5, 65.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(239.1, 65.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(237.7, 65.1);
            std::thread::sleep(Duration::from_millis(56));
            let _ = robot.mouse_move(235.9, 65.1);
            let _ = robot.mouse_move(233.6, 65.1);
            let _ = robot.mouse_move(231.3, 65.1);
            let _ = robot.mouse_move(228.4, 65.1);
            let _ = robot.mouse_move(224.8, 65.1);
            let _ = robot.mouse_move(221.7, 65.1);
            let _ = robot.mouse_move(218.7, 65.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(215.7, 65.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(212.1, 64.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(209.0, 64.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(205.4, 64.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(200.9, 64.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(196.3, 63.5);
            std::thread::sleep(Duration::from_millis(69));
            let _ = robot.mouse_move(190.9, 62.9);
            let _ = robot.mouse_move(185.4, 62.3);
            let _ = robot.mouse_move(179.8, 61.7);
            let _ = robot.mouse_move(175.0, 61.1);
            let _ = robot.mouse_move(170.4, 61.1);
            let _ = robot.mouse_move(165.8, 60.5);
            let _ = robot.mouse_move(160.4, 59.9);
            let _ = robot.mouse_move(154.0, 59.3);
            let _ = robot.mouse_move(148.3, 59.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(141.9, 58.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(137.7, 58.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(133.3, 58.0);
            std::thread::sleep(Duration::from_millis(56));
            let _ = robot.mouse_move(129.4, 57.5);
            let _ = robot.mouse_move(126.3, 57.5);
            let _ = robot.mouse_move(122.7, 57.5);
            let _ = robot.mouse_move(118.9, 57.5);
            let _ = robot.mouse_move(115.8, 57.5);
            let _ = robot.mouse_move(113.4, 57.5);
            let _ = robot.mouse_move(111.6, 57.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(109.7, 57.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(108.4, 57.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(107.0, 57.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(106.0, 57.5);
            std::thread::sleep(Duration::from_millis(68));
            let _ = robot.mouse_move(105.2, 57.5);
            std::thread::sleep(Duration::from_millis(34));
            let _ = robot.mouse_down();
            std::thread::sleep(Duration::from_millis(50));
            let _ = robot.mouse_up();
            std::thread::sleep(Duration::from_millis(224));
            let _ = robot.mouse_move(105.2, 58.1);
            std::thread::sleep(Duration::from_millis(16));
            let _ = robot.mouse_move(106.1, 59.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(106.6, 60.4);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(107.0, 61.4);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(107.5, 62.3);
            std::thread::sleep(Duration::from_millis(69));
            let _ = robot.mouse_move(108.0, 63.2);
            let _ = robot.mouse_move(108.4, 64.1);
            let _ = robot.mouse_move(109.4, 65.5);
            let _ = robot.mouse_move(109.8, 66.9);
            let _ = robot.mouse_move(110.7, 68.3);
            let _ = robot.mouse_move(111.7, 70.1);
            let _ = robot.mouse_move(112.6, 71.5);
            let _ = robot.mouse_move(113.5, 72.9);
            let _ = robot.mouse_move(114.9, 74.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(115.8, 76.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(117.7, 78.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(119.8, 81.1);
            std::thread::sleep(Duration::from_millis(56));
            let _ = robot.mouse_move(122.6, 85.7);
            let _ = robot.mouse_move(128.2, 92.7);
            let _ = robot.mouse_move(134.6, 102.2);
            let _ = robot.mouse_move(142.5, 114.5);
            let _ = robot.mouse_move(150.8, 127.3);
            let _ = robot.mouse_move(158.1, 141.2);
            let _ = robot.mouse_move(164.5, 153.8);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(170.5, 165.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(175.4, 174.8);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(180.1, 184.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(187.0, 197.2);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(195.3, 211.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(204.6, 225.8);
            std::thread::sleep(Duration::from_millis(69));
            let _ = robot.mouse_move(212.9, 239.7);
            let _ = robot.mouse_move(220.2, 252.6);
            let _ = robot.mouse_move(227.1, 262.9);
            let _ = robot.mouse_move(232.8, 271.8);
            let _ = robot.mouse_move(237.2, 279.2);
            let _ = robot.mouse_move(242.4, 286.6);
            let _ = robot.mouse_move(246.8, 293.9);
            let _ = robot.mouse_move(251.0, 300.2);
            let _ = robot.mouse_move(255.1, 306.4);
            std::thread::sleep(Duration::from_millis(13));
            let _ = robot.mouse_move(258.3, 310.9);
            let _ = robot.mouse_move(261.2, 314.4);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(263.4, 317.1);
            std::thread::sleep(Duration::from_millis(56));
            let _ = robot.mouse_move(264.9, 319.0);
            let _ = robot.mouse_move(265.8, 320.4);
            let _ = robot.mouse_move(266.7, 321.4);
            let _ = robot.mouse_move(267.2, 322.3);
            let _ = robot.mouse_move(268.1, 323.2);
            let _ = robot.mouse_move(268.6, 324.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(269.9, 326.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(270.9, 327.4);
            std::thread::sleep(Duration::from_millis(21));
            let _ = robot.mouse_move(272.2, 329.2);
            let _ = robot.mouse_move(273.2, 331.0);
            std::thread::sleep(Duration::from_millis(17));
            let _ = robot.mouse_move(274.1, 332.0);
            let _ = robot.mouse_move(275.0, 332.9);
            std::thread::sleep(Duration::from_millis(15));
            let _ = robot.mouse_move(275.5, 333.8);
            std::thread::sleep(Duration::from_millis(28));
            let _ = robot.mouse_move(275.8, 334.6);
            std::thread::sleep(Duration::from_millis(807));
            let _ = robot.mouse_move(276.6, 334.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(277.6, 334.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(278.5, 334.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(279.9, 334.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(281.3, 333.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(283.1, 333.6);
            std::thread::sleep(Duration::from_millis(56));
            let _ = robot.mouse_move(285.4, 333.6);
            let _ = robot.mouse_move(290.3, 333.1);
            let _ = robot.mouse_move(299.3, 331.7);
            let _ = robot.mouse_move(312.8, 330.0);
            let _ = robot.mouse_move(330.2, 328.2);
            let _ = robot.mouse_move(346.8, 326.3);
            let _ = robot.mouse_move(361.5, 325.4);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(374.6, 324.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(386.3, 323.7);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(398.9, 322.8);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(411.7, 322.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(424.5, 320.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(438.6, 318.5);
            std::thread::sleep(Duration::from_millis(69));
            let _ = robot.mouse_move(451.8, 316.8);
            let _ = robot.mouse_move(463.5, 314.2);
            let _ = robot.mouse_move(472.9, 312.7);
            let _ = robot.mouse_move(480.9, 311.2);
            let _ = robot.mouse_move(487.8, 309.2);
            let _ = robot.mouse_move(493.6, 307.9);
            let _ = robot.mouse_move(498.4, 306.7);
            let _ = robot.mouse_move(502.4, 305.5);
            let _ = robot.mouse_move(505.6, 304.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(508.0, 303.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(509.9, 302.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(511.7, 301.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(513.1, 300.7);
            std::thread::sleep(Duration::from_millis(48));
            let _ = robot.mouse_move(514.9, 300.3);
            let _ = robot.mouse_move(516.3, 299.8);
            let _ = robot.mouse_move(517.7, 299.3);
            let _ = robot.mouse_move(519.6, 298.9);
            let _ = robot.mouse_move(522.4, 297.9);
            let _ = robot.mouse_move(526.1, 296.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(530.8, 294.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(534.8, 292.8);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(538.7, 291.2);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(542.1, 289.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(545.9, 287.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(549.2, 285.7);
            std::thread::sleep(Duration::from_millis(85));
            let _ = robot.mouse_move(552.9, 284.6);
            let _ = robot.mouse_move(556.8, 282.9);
            let _ = robot.mouse_move(561.4, 281.8);
            let _ = robot.mouse_move(567.7, 279.9);
            let _ = robot.mouse_move(574.4, 277.9);
            let _ = robot.mouse_move(583.0, 275.0);
            let _ = robot.mouse_move(592.1, 272.0);
            let _ = robot.mouse_move(601.4, 267.3);
            let _ = robot.mouse_move(612.2, 260.7);
            let _ = robot.mouse_move(622.6, 252.0);
            let _ = robot.mouse_move(634.4, 242.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(647.3, 230.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(659.3, 217.1);
            std::thread::sleep(Duration::from_millis(31));
            let _ = robot.mouse_move(672.2, 204.2);
            let _ = robot.mouse_move(684.2, 190.4);
            let _ = robot.mouse_move(697.1, 176.5);
            let _ = robot.mouse_move(709.1, 164.5);
            std::thread::sleep(Duration::from_millis(6));
            let _ = robot.mouse_move(719.3, 152.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(728.2, 142.7);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(735.7, 133.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(741.1, 126.7);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(745.3, 120.4);
            std::thread::sleep(Duration::from_millis(9));
            let _ = robot.mouse_move(747.8, 115.9);
            std::thread::sleep(Duration::from_millis(17));
            let _ = robot.mouse_move(750.0, 112.6);
            let _ = robot.mouse_move(751.1, 110.0);
            std::thread::sleep(Duration::from_millis(84));
            let _ = robot.mouse_move(752.5, 107.6);
            let _ = robot.mouse_move(753.4, 106.2);
            let _ = robot.mouse_move(753.9, 104.8);
            let _ = robot.mouse_move(754.4, 103.9);
            let _ = robot.mouse_move(754.8, 103.0);
            let _ = robot.mouse_move(755.6, 102.2);
            std::thread::sleep(Duration::from_millis(15));
            let _ = robot.mouse_move(756.0, 100.8);
            std::thread::sleep(Duration::from_millis(49));
            let _ = robot.mouse_move(757.0, 99.8);
            let _ = robot.mouse_move(757.4, 98.9);
            std::thread::sleep(Duration::from_millis(263));
            let _ = robot.mouse_move(757.4, 97.9);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(757.9, 95.5);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(758.3, 93.2);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(758.8, 90.4);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(758.8, 88.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(759.3, 85.7);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(759.3, 83.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(759.7, 81.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(760.2, 79.7);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(760.2, 77.8);
            std::thread::sleep(Duration::from_millis(14));
            let _ = robot.mouse_move(760.7, 75.5);
            std::thread::sleep(Duration::from_millis(100));
            let _ = robot.mouse_move(760.7, 73.7);
            let _ = robot.mouse_move(760.7, 71.8);
            let _ = robot.mouse_move(760.7, 69.5);
            let _ = robot.mouse_move(761.1, 67.7);
            let _ = robot.mouse_move(761.1, 65.3);
            let _ = robot.mouse_move(761.1, 63.5);
            let _ = robot.mouse_move(761.1, 61.2);
            let _ = robot.mouse_move(761.6, 59.3);
            let _ = robot.mouse_move(761.6, 58.0);
            let _ = robot.mouse_move(761.6, 56.6);
            let _ = robot.mouse_move(761.6, 54.7);
            let _ = robot.mouse_move(761.6, 53.3);
            let _ = robot.mouse_move(761.6, 52.0);
            std::thread::sleep(Duration::from_millis(16));
            let _ = robot.mouse_move(761.6, 50.1);
            let _ = robot.mouse_move(762.0, 48.3);
            let _ = robot.mouse_move(762.5, 46.4);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(763.0, 44.6);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(763.4, 43.2);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(763.9, 41.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(764.3, 40.0);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(764.8, 38.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(765.3, 36.3);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(766.2, 34.4);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(766.7, 32.6);
            std::thread::sleep(Duration::from_millis(14));
            let _ = robot.mouse_move(767.1, 31.2);
            std::thread::sleep(Duration::from_millis(100));
            let _ = robot.mouse_move(768.0, 29.3);
            let _ = robot.mouse_move(768.5, 27.5);
            let _ = robot.mouse_move(769.4, 26.1);
            let _ = robot.mouse_move(770.3, 23.8);
            let _ = robot.mouse_move(771.7, 21.9);
            let _ = robot.mouse_move(773.2, 19.6);
            let _ = robot.mouse_move(775.1, 17.6);
            let _ = robot.mouse_move(776.1, 15.2);
            let _ = robot.mouse_move(777.5, 13.4);
            let _ = robot.mouse_move(778.4, 12.0);
            let _ = robot.mouse_move(779.3, 10.1);
            let _ = robot.mouse_move(779.8, 8.8);
            let _ = robot.mouse_move(780.2, 7.4);
            std::thread::sleep(Duration::from_millis(17));
            let _ = robot.mouse_move(780.7, 6.0);
            let _ = robot.mouse_move(781.2, 5.1);
            let _ = robot.mouse_move(781.2, 4.1);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(781.6, 3.2);
            std::thread::sleep(Duration::from_millis(8));
            let _ = robot.mouse_move(781.6, 2.3);
            std::thread::sleep(Duration::from_millis(16));
            let _ = robot.mouse_move(782.1, 0.9);

            std::thread::sleep(Duration::from_secs(1));
            let _ = robot.exit();
        })
        .run(|| {
            desktop_app::app::combined_app();
        });
}
